DML2_Assgn.insert_dml();
DML2_Assgn.updating_dml();

/*
Assignment – 05 December 2022
•	Create a class DML2_Assgn
o	Create a method insert_dml
	Insert a two or more record in account object  with yourname + ‘Assignment’.
•	Create a method for updating_dml	
	Insert one record in Account Object with the name ‘Account Created’.
	Update the name of the same record by updating name to ‘Account Updated’.
•	Create an anonymous apex DML2_Anonymous.apex and call the methods created above.
*/
